# ----------------------------------------------------------------------
# Copyright (c) 2021, 2022 Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0
# ----------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: ""
nameSuffix: ""
commonLabels:
  version: 0.0.1
  app.kubernetes.io/version: 0.0.1
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: pixelstreaming-stack

# add components
bases:
  - turn
  - streaming
  - routing

# patches (defer to overlay)
patchesJson6902: []

# image substitutions (defer to overlay)
images: []
